# Generated by Django 4.2.7 on 2023-11-22 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('flag', models.ImageField(upload_to='teams/flags/', verbose_name='Flag Image')),
                ('emblem', models.ImageField(upload_to='teams/emblems/', verbose_name='Team Emblem')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('photo', models.ImageField(upload_to='players/', verbose_name='Player Photo')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('jersey_number', models.PositiveIntegerField(verbose_name='Jersey Number')),
                ('is_starter', models.BooleanField(default=False, verbose_name='Is Starter?')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playingposition', verbose_name='Playing Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='Team')),
            ],
        ),
    ]
