# Generated by Django 4.2.7 on 2023-11-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='playingposition',
            options={'verbose_name': 'Posición de Juego', 'verbose_name_plural': 'Posiciones de Juego'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_starter',
            field=models.BooleanField(default=False, verbose_name='¿Es titular?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(verbose_name='Numero de jugador'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='players/', verbose_name='Foto del jugador'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playingposition', verbose_name='Posicion en la que juega'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='playingposition',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='playingposition',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='team',
            name='emblem',
            field=models.ImageField(upload_to='teams/emblems/', verbose_name='Emblema equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(upload_to='teams/flags/', verbose_name='Imagen bandera'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del equipo'),
        ),
    ]
