# Generated by Django 4.2.7 on 2023-11-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tecnico_remove_team_usuario_team_tecnico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnicos'},
        ),
    ]
