# Generated by Django 4.2.7 on 2023-11-25 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tecniconacionality_tecnicorol_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tecniconacionality', verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tecnicorol', verbose_name='Rol'),
        ),
    ]
