# Generated by Django 4.2.7 on 2023-11-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
